Abaca_plant
Bract_brown_streaks
Brown_border_streaks
Brown_leaf_margin
Brown_streaks_lamina
Corrugated_leaf
Corrugated_petiole
Dark_green_spindle_streaks_petiole
Dark_green_spots_patches_petiole
Dark_green_thick_veins
Dashes_lamina
Dots_patches_midrib
Dots_spots_lamina
Failed_leaf_unfurling
Green_streaks
Green_yellow_streaks
Light_green_patches_petiole
Light_green_streaks
Light_green_thick_veins
Narrow_leaf
Necrotic_edge
Necrotic_lamina
Necrotic_midrib
Oval_streaks
Petiole_breaking
Petiole_yellow_streaks
Restricted_leaf_growth
Rosetting
Rusty_yellow_dots
Rusty_yellow_streaks
Shoe_stringing
Stunting
Thick_leaf_veins
Upward_curling
White_patches
White_patches_pseudostem
White_streaks
White_thick_veins
Wrikled_leaf
Wrinkled_leaf
Wrinkled_petiole
Yellow_brown_lamina
Yellow_brown_leaf_lamina
Yellow_edge
Yellow_leaf_lamina
Yellow_patches_green_lamina
Yellow_patches_lamina
Yellow_streaks_green_lamina
Yellow_streaks_lamina
Yellow_thick_veins
